name: CI/CD Scaleway

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build-Deploy-Scaleway-Containers:
    runs-on: ubuntu-latest
    name: Deploy to Scaleway Containers
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Api to Scaleway Container Registry
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: Dockerfile
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/weatherapi:${{ github.sha }}
          labels: |
            repo=${{ github.repository }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
